vehicle_controller:
  ros__parameters:
    odom_topic: "/ins/odometry"
    imu_topic: "/ins/imu"
    command_topic: "/command"
    enable_topic: "/enable"
    record_topic: "/controller_record"
    controller:
      lateral: "mpc"
      longitudinal: "lqr"

    sim:
      dt: 0.10
      progress_window: 80

    speed:
      mode: "profile"
      constant_value: 10.0
      profile: "referencePath_Velocity_peak_velocity_3"

    accel_limits:
      a_max: 3.372
      a_min: -7.357

    mpc_combined:
      N: 25
      Q: [15.0, 12.0, 8.0, 10.0, 8.0, 20.0]
      R: [5.0, 0.5]
      Rd: [15.0, 2.0]
      kappa_ff_gain: 0.5
      max_steer: 0.6108652382
      a_min: -7.357
      a_max: 3.372

    mpc:
      N: 25
      Q: [15.0, 12.0, 8.0, 10.0]
      R: 5.0
      Rd: 15.0
      kappa_ff_gain: 0.5
      max_steer: 0.6108652382

    lon_lqr:
      Q: [20.0, 10.0]
      R: 0.4
      a_min: -7.357
      a_max: 3.372
      int_error_min: -10.0
      int_error_max: 10.0

    timing:
      dt_min: 0.05
      dt_max: 0.10
      min_control_period: 0.10

    end_condition:
      max_lateral_error: 7.0
      max_longitudinal_error: 7.0
      goal_index_margin: 3
      goal_lateral_error: 2.0
      goal_longitudinal_error: 2.0
      goal_heading_error: 0.0872664626
      goal_speed_threshold: 0.2
