vehicle_controller:
  ros__parameters:
    vehicle.mass: 1948.0
    vehicle.wheelbase: 2.720
    vehicle.lr: 1.506

    vehicle.aero_a: 45.0
    vehicle.aero_b: 10.0
    vehicle.aero_c: 0.518

    vehicle.max_steer: 0.6108652382
    vehicle.max_steer_rate: 0.6108652382
    vehicle.steering_sign: -1.0
    vehicle.max_pedal_publish: 0.60

    vehicle.sensor_offset_x: 1.14
    vehicle.sensor_offset_y: 0.32
    vehicle.sensor_offset_z: 0.0

    vehicle.accel_map_file: "data/Acc_mapData_noSlope.mat"
    vehicle.brake_map_file: "data/brake_mapData_noSlope.mat"
