vehicle_controller:
  ros__parameters:
    vehicle:
      mass: 2070.0
      wheelbase: 2.720
      lf: 1.214
      lr: 1.506
      iz: 2500.0

      aero_a: 45.0
      aero_b: 10.0
      aero_c: 0.518

      max_steer: 0.6108652382
      max_steer_rate: 0.6981317008
      max_pedal_publish: 0.60

      tire:
        front:
          b: 9.5
          c: 1.30
          d: 8000.0
          calpha: 98800.0
        rear:
          b: 10.5
          c: 1.30
          d: 8500.0
          calpha: 116025.0

      accel_map_file: "data/Acc_mapData_noSlope.mat"
      brake_map_file: "data/brake_mapData_noSlope.mat"
